name: Build Rootful DEB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.app
          xcodebuild -version

      - name: Build tvOS Project
        run: |
          xcodebuild \
            -project MinecraftStorageFix.xcodeproj \
            -scheme MinecraftStorageFix \
            -configuration Release \
            -sdk appletvos \
            BUILD_DIR=build \
            clean build

      - name: Install dpkg
        run: brew install dpkg

      - name: Create package structure
        run: |
          mkdir -p package/Library/Frameworks
          mkdir -p package/DEBIAN

          cp -R build/Release-appletvos/MinecraftStorageFix.framework \
          package/Library/Frameworks/

      - name: Create control file
        run: |
          cat <<EOF > package/DEBIAN/control
          Package: com.fauxly.minecraftstoragefix
          Name: MinecraftStorageFix
          Version: 1.0
          Architecture: iphoneos-arm
          Description: Minecraft Storage Fix for tvOS
          Maintainer: Fauxly
          Author: Fauxly
          Section: Tweaks
          Priority: optional
          Depends: firmware (>= 14.0)
          EOF

      - name: Build DEB package
        run: |
          dpkg-deb --build package
          mv package.deb MinecraftStorageFix_rootful.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftStorageFix_rootful
          path: MinecraftStorageFix_rootful.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          files: MinecraftStorageFix_rootful.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
